environment:
  stack_root: 'C:\sr'
  tmp: 'C:\tmp'

cache:
  - '%LocalAppData%\Programs\stack -> stack.yaml'
  - 'C:\sr'

before_build:
  - choco install haskell-stack

build_script:
  - stack --no-terminal --install-ghc --local-bin-path . install

after_build:
  - 7z a vban-test-windows.zip vban-test-exe.exe

artifacts:
  - path: vban-test-windows.zip
    name: Release
